FROM clickhouse/clickhouse-server:latest

# Remove the built-in config.d file we don’t want
RUN rm -f /etc/clickhouse-server/config.d/docker_related_config.xml

# Copy in your fixed config.xml (with user_directories + stream_like_engine_allow_direct_select=1)
COPY clickhouse-config/config.xml /etc/clickhouse-server/config.xml

USER clickhouse
ENTRYPOINT ["/usr/bin/clickhouse-server", "--config-file=/etc/clickhouse-server/config.xml"]
